# Generated by Django 4.0.1 on 2022-01-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'BusinessOwner'), (3, 'EndUser'), (4, 'StaffUser')], default=3),
        ),
    ]
