# Generated by Django 4.0.1 on 2022-01-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmailVerification',
        ),
    ]
