# Generated by Django 4.0.1 on 2022-02-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_otp_user_otp_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Business Owner'), (3, 'EndUser'), (4, 'StaffUser')], default=3),
        ),
    ]
