# Generated by Django 4.0.1 on 2022-01-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_useremailverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userphoneverification',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
