# Generated by Django 4.0.1 on 2022-02-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('identity_proof', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('lat', models.CharField(max_length=256)),
                ('long', models.CharField(max_length=256)),
                ('level', models.IntegerField(max_length=20)),
                ('company_name', models.CharField(max_length=256)),
                ('company_email', models.CharField(max_length=256)),
                ('license', models.CharField(max_length=256)),
                ('company_phone', models.CharField(max_length=256)),
                ('company_polices', models.TextField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
