# Generated by Django 4.0.1 on 2022-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businessdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='level',
            field=models.IntegerField(),
        ),
    ]
