# Generated by Django 4.0.1 on 2022-02-08 09:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_businessdetail_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdetail',
            old_name='long',
            new_name='lng',
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='company_email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='company_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='company_phone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='company_polices',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='identity_proof',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='license',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
