# Generated by Django 4.0.1 on 2022-02-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_migration'),
        ('accounts', '0010_alter_businessdetail_identity_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='aminities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.amenities'),
        ),
    ]
