# Generated by Django 4.0.1 on 2022-02-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_businessdetail_aminities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='aminities',
        ),
    ]
