version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: dev-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/usr/src/app
      - ./devlogdna:/var/log/nginx
    depends_on:
      - web
    networks:
      - dev-network
      
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-django
    restart: always
    command: bash -c "pip3 install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn wqtah.wsgi -b 0.0.0.0:80"
    volumes:
      - .:/usr/src/app
    expose:
      - "80"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
