# Generated by Django 4.0.1 on 2022-02-09 06:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('identity_proof', models.FileField(upload_to='media')),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.CharField(blank=True, max_length=256, null=True)),
                ('lng', models.CharField(blank=True, max_length=256, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, choices=[(1, 'Add Business'), (2, 'Company Detail'), (3, 'Profile Completed')], null=True)),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('company_email', models.CharField(blank=True, max_length=256, null=True)),
                ('license', models.CharField(blank=True, max_length=256, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('company_policies', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.CharField(blank=True, max_length=256, null=True)),
                ('lng', models.CharField(blank=True, max_length=256, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.categories')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlotService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceMediaMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('1', 'image'), ('2', 'video')], max_length=2, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='post_attachments')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post_attachments_thumbnail')),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.amenities')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessProfileMediaMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('1', 'image'), ('2', 'video')], max_length=2, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='post_attachments')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post_attachments_thumbnail')),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessProfileAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.amenities')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
