# Generated by Django 4.0.1 on 2022-02-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_businessdetail_aminities'),
        ('business', '0001_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.businessdetail'),
        ),
    ]
