# Generated by Django 4.0.1 on 2022-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='company_policies',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='company_country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='identity_file_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_company_policies_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Add Business'), (2, 'Company Detail'), (4, 'Profile Completed')], null=True),
        ),
    ]
