# Generated by Django 4.0.1 on 2022-02-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='amenities',
            field=models.JSONField(default=list),
        ),
    ]
